"""
Wan 2.2 Runner — Safebox Local Service v1.0

Wraps Alibaba's Wan 2.2 (Apache 2.0) as a Safebox-canonical text-to-video
and image-to-video service. Mixture-of-Experts diffusion model with separate
high-noise and low-noise experts — 27B parameters total, ~14B active per
denoising step, kept VRAM footprint near 14B-class.

Sister runner to ltx-video/. Same /v1/video/generate protocol, different
model behind it. Pick LTX-Video for speed (8-step distilled inference) and
Wan 2.2 for quality (MoE produces sharper detail and better prompt adherence
at the cost of 30-40 step inference).

Endpoints (Safebox canonical):
    POST /v1/video/generate    — text → MP4 (or image+text → MP4)
    GET  /v1/capabilities
    GET  /v1/capacity
    GET  /v1/models
    GET  /health

Models supported via manifests:
  - wan-2-2-ti2v-5b      Combined T2V+I2V, 5B params, ~16GB VRAM with offload
  - wan-2-2-t2v-a14b     T2V only, A14B (27B total, 14B active), 24GB+ VRAM
  - wan-2-2-i2v-a14b     I2V only, A14B, 24GB+ VRAM

Output is MP4 via ffmpeg. Audio is NOT generated by base Wan 2.2 — for
synchronized audio+video, use the ltx-video runner instead. (Wan 2.2-S2V
is a separate audio-driven variant covering speech-to-video; not in this
v1 wrapper.)
"""

import asyncio
import base64
import collections
import hashlib
import hmac
import io
import json
import logging
import os
import socket
import stat
import subprocess
import time
import uuid
from pathlib import Path
from typing import Any, Dict, List, Optional, Set

from fastapi import FastAPI, HTTPException, Request
from fastapi.responses import JSONResponse, Response
from pydantic import BaseModel, Field
import uvicorn


# ─── Logging ───────────────────────────────────────────────────────────
logger = logging.getLogger("wan-video-runner")
logging.basicConfig(level=logging.INFO,
                    format="%(asctime)s %(levelname)s %(message)s")


# ─── Configuration ─────────────────────────────────────────────────────
RUNNER_ID  = os.getenv("RUNNER_ID",  "safebox-wan-video-1")
SERVICE_ID = os.getenv("SERVICE_ID", "video-2")
HMAC_KEY_PATH = os.getenv("HMAC_KEY_PATH", "/etc/safebox/model-api.key")
REQUIRE_HMAC  = os.getenv("SAFEBOX_REQUIRE_HMAC", "false").lower() == "true"

SAFEBOX_SOCKET_PATH = os.getenv("SAFEBOX_SOCKET_PATH",
                                 f"/run/safebox/services/{SERVICE_ID}.sock")
ENABLE_UNIX_SOCKET  = os.getenv("ENABLE_UNIX_SOCKET", "true").lower() == "true"

MODEL_NAME    = os.getenv("MODEL_NAME",      "wan-2-2-ti2v-5b")
WAN_MODEL_PATH = os.getenv("WAN_MODEL_PATH", "Wan-AI/Wan2.2-TI2V-5B-Diffusers")
WAN_VARIANT    = os.getenv("WAN_VARIANT",    "ti2v-5b")   # ti2v-5b | t2v-a14b | i2v-a14b

# Wan 2.2 native resolutions: 720p (720x1280 portrait or 1280x720 landscape)
# and 480p. Frame counts: 81 for ~5s at 16fps, or 121 for ~7.5s at 16fps (5B)
DEFAULT_WIDTH       = int(os.getenv("DEFAULT_WIDTH",      "1280"))
DEFAULT_HEIGHT      = int(os.getenv("DEFAULT_HEIGHT",     "720"))
DEFAULT_NUM_FRAMES  = int(os.getenv("DEFAULT_NUM_FRAMES", "81"))
DEFAULT_FPS         = int(os.getenv("DEFAULT_FPS",        "16"))
DEFAULT_STEPS       = int(os.getenv("DEFAULT_STEPS",      "40"))
# Wan 2.2's MoE has two guidance scales — one per expert. The runner exposes
# `guidance` (high-noise expert) and `guidanceLowNoise` (low-noise expert).
DEFAULT_GUIDANCE         = float(os.getenv("DEFAULT_GUIDANCE",          "4.0"))
DEFAULT_GUIDANCE_LOW_NOISE = float(os.getenv("DEFAULT_GUIDANCE_LOW_NOISE","3.0"))
DEFAULT_FLOW_SHIFT       = float(os.getenv("DEFAULT_FLOW_SHIFT",        "5.0"))   # 5.0 for 720p, 3.0 for 480p
MAX_NUM_FRAMES           = int(os.getenv("MAX_NUM_FRAMES",              "121"))

ENABLE_CPU_OFFLOAD       = os.getenv("ENABLE_CPU_OFFLOAD",  "true").lower() == "true"

MAX_QUEUE_DEPTH = int(os.getenv("MAX_QUEUE_DEPTH",  "1"))
WORK_DIR = Path(os.getenv("WAN_WORK_DIR", "/data/output"))
WORK_DIR.mkdir(parents=True, exist_ok=True)

CAP_TEXT2VIDEO   = os.getenv("CAP_TEXT2VIDEO",  "true").lower()  == "true"
CAP_IMAGE2VIDEO  = os.getenv("CAP_IMAGE2VIDEO", "true").lower()  == "true"
CAP_VIDEO2VIDEO  = os.getenv("CAP_VIDEO2VIDEO", "false").lower() == "true"
CAP_AUDIO        = False  # Base Wan 2.2 is video-only; -S2V is a separate variant not in this runner
CAP_STREAMING    = False

# Load HMAC key
try:
    with open(HMAC_KEY_PATH) as f:
        HMAC_KEY = f.read().strip()
except Exception as e:
    if REQUIRE_HMAC:
        logger.error(f"HMAC required but key unavailable: {e}")
        raise
    HMAC_KEY = None
    logger.info("HMAC verification disabled (no key, and SAFEBOX_REQUIRE_HMAC=false)")


# ─── State ─────────────────────────────────────────────────────────────
in_flight:   int  = 0
request_count: int = 0
total_frames_generated: int = 0
total_video_seconds: float = 0.0
total_compute_ms: int = 0
seen_nonces = collections.OrderedDict()  # nonce -> timestamp_sec (insertion-ordered)
# ─── Pydantic request model ────────────────────────────────────────────
class VideoGenerateRequest(BaseModel):
    model:             str
    prompt:            str = Field(..., description="Text prompt")
    negativePrompt:    Optional[str]   = ""
    inputImage:        Optional[str]   = None
    width:             Optional[int]   = None
    height:            Optional[int]   = None
    numFrames:         Optional[int]   = None
    fps:               Optional[int]   = None
    steps:             Optional[int]   = None
    guidance:          Optional[float] = None
    guidanceLowNoise:  Optional[float] = None    # Wan 2.2 MoE second guidance scale
    flowShift:         Optional[float] = None    # 5.0 for 720p, 3.0 for 480p
    seed:              Optional[int]   = None
    outputMode:        Optional[str]   = "path"
    filenamePrefix:    Optional[str]   = "safebox-wan-video"


# ─── App ───────────────────────────────────────────────────────────────
app = FastAPI(title="Wan 2.2 Safebox Runner", version="1.0")


# ─── HMAC verification ─────────────────────────────────────────────────

# ── Shared canonical HMAC (single source of truth) ──────────────────────
# safebox_auth.py is vendored beside runner.py from model-runners/_shared/
# via sync-shared.sh, and COPYed into /app/ by the Dockerfile.
from safebox_auth import verify_hmac as _sb_verify  # noqa: E402

def verify_hmac(request: Request, body: bytes) -> bool:
    # Canonical HMAC verification lives in ONE place: model-runners/_shared/
    # safebox_auth.py, whose canonical string matches auth.js and the Safebox
    # LocalRunner byte-for-byte. This delegation keeps the call sites unchanged
    # while ensuring every runner shares a single source of truth.
    return _sb_verify(request, body)
def get_capacity_hint() -> str:
    if MAX_QUEUE_DEPTH <= 1:
        return "saturated" if in_flight >= 1 else "available"
    if in_flight >= MAX_QUEUE_DEPTH * 0.9: return "saturated"
    if in_flight >= MAX_QUEUE_DEPTH * 0.7: return "near-saturated"
    return "available"


def safebox_headers(request_id: str, model: str, compute_ms: int = 0
                    ) -> Dict[str, str]:
    return {
        "X-Safebox-Request-Id":    request_id,
        "X-Safebox-Runner-Id":     RUNNER_ID,
        "X-Safebox-Model-Id":      model,
        "X-Safebox-Compute-Ms":    str(compute_ms),
        "X-Safebox-Capacity-Hint": get_capacity_hint(),
    }


def model_matches(requested: str) -> bool:
    if not requested:
        return False
    if requested == MODEL_NAME:
        return True
    if requested == WAN_MODEL_PATH:
        return True
    if "/" in WAN_MODEL_PATH and requested == WAN_MODEL_PATH.rsplit("/", 1)[-1]:
        return True
    return False


def resolve_input_image(input_image: Optional[str]) -> Optional[bytes]:
    if not input_image:
        return None
    if input_image.startswith("data:"):
        try:
            comma = input_image.find(",")
            return base64.b64decode(input_image[comma+1:])
        except Exception as e:
            raise ValueError(f"Bad data: URL: {e}")
    p = Path(input_image)
    if not p.exists():
        raise ValueError(f"inputImage not found: {input_image}")
    return p.read_bytes()


def frames_to_mp4(frames, fps: int, out_path: Path) -> int:
    """Encode a sequence of numpy frames [N, H, W, 3] uint8 into MP4 via
    ffmpeg piping raw frames. Returns the byte size of the written file."""
    import numpy as np
    if not hasattr(frames, "shape"):
        frames = np.asarray(frames)
    if frames.dtype.kind == "f":
        frames = (frames.clip(0, 1) * 255).astype("uint8")
    n, h, w, c = frames.shape
    assert c == 3, f"Expected 3 channels, got {c}"
    cmd = [
        "ffmpeg", "-y", "-loglevel", "error",
        "-f", "rawvideo", "-pix_fmt", "rgb24",
        "-s", f"{w}x{h}", "-r", str(fps),
        "-i", "pipe:0",
        "-c:v", "libx264", "-pix_fmt", "yuv420p",
        "-preset", "fast", "-crf", "19",
        str(out_path),
    ]
    p = subprocess.run(cmd, input=frames.tobytes(), capture_output=True)
    if p.returncode != 0:
        raise RuntimeError(f"ffmpeg failed: {p.stderr.decode('utf-8', errors='replace')}")
    return out_path.stat().st_size


# ─── Wan 2.2 wrapper ───────────────────────────────────────────────────
class WanVideoRunner:
    """Lazily import diffusers + Wan-AI pipeline. Pipeline selection depends
    on WAN_VARIANT — text-to-video, image-to-video, or combined."""

    def __init__(self):
        self.ready    = False
        self.pipeline = None
        self.device   = "cpu"
        self._is_i2v  = False   # whether the loaded pipeline expects an image input

    def load(self):
        if self.ready:
            return
        try:
            import torch
            from diffusers import AutoencoderKLWan
            # Pick the right pipeline class based on the variant
            if WAN_VARIANT == "i2v-a14b":
                from diffusers import WanImageToVideoPipeline  # type: ignore
                pipe_cls = WanImageToVideoPipeline
                self._is_i2v = True
            else:
                # T2V-A14B and TI2V-5B both use WanPipeline (TI2V accepts an
                # optional image at call time)
                from diffusers import WanPipeline  # type: ignore
                pipe_cls = WanPipeline
                self._is_i2v = False
        except Exception as e:
            logger.error(f"Failed to import diffusers Wan pipeline / torch: {e}")
            raise
        logger.info(f"Loading Wan 2.2 — model_path={WAN_MODEL_PATH} variant={WAN_VARIANT}")
        self.device = "cuda" if torch.cuda.is_available() else "cpu"

        vae = AutoencoderKLWan.from_pretrained(
            WAN_MODEL_PATH, subfolder="vae",
            torch_dtype=torch.float32,
        )
        self.pipeline = pipe_cls.from_pretrained(
            WAN_MODEL_PATH, vae=vae,
            torch_dtype=torch.bfloat16 if self.device == "cuda" else torch.float32,
        )

        # CPU offload — Wan A14B variants need this to fit on consumer cards
        if self.device == "cuda" and ENABLE_CPU_OFFLOAD:
            try:
                self.pipeline.enable_model_cpu_offload()
            except Exception as e:
                logger.warning(f"enable_model_cpu_offload failed (continuing): {e}")
                self.pipeline = self.pipeline.to(self.device)
        else:
            self.pipeline = self.pipeline.to(self.device)
        self.ready = True
        logger.info(f"Wan 2.2 ready — device={self.device} i2v_pipeline={self._is_i2v}")

    def generate(self, req: VideoGenerateRequest) -> Dict[str, Any]:
        self.load()
        import torch

        width  = req.width  or DEFAULT_WIDTH
        height = req.height or DEFAULT_HEIGHT
        # Wan 2.2 expects dimensions divisible by 16 (VAE downsample factor)
        width  = (width  // 16) * 16
        height = (height // 16) * 16
        if width <= 0 or height <= 0:
            raise ValueError(f"width and height must be > 0 (got {width}x{height})")

        n_frames = req.numFrames or DEFAULT_NUM_FRAMES
        if n_frames > MAX_NUM_FRAMES:
            raise ValueError(f"numFrames {n_frames} exceeds MAX_NUM_FRAMES {MAX_NUM_FRAMES}")
        if n_frames <= 0:
            raise ValueError("numFrames must be > 0")

        fps              = req.fps               or DEFAULT_FPS
        steps            = req.steps             or DEFAULT_STEPS
        guidance         = req.guidance          or DEFAULT_GUIDANCE
        guidance_low     = req.guidanceLowNoise  or DEFAULT_GUIDANCE_LOW_NOISE
        flow_shift       = req.flowShift         or DEFAULT_FLOW_SHIFT
        seed             = req.seed if req.seed is not None else int.from_bytes(os.urandom(8), "big") % (2**31)

        t0 = time.time()
        source_payload = {
            "prompt": req.prompt, "negativePrompt": req.negativePrompt,
            "width": width, "height": height,
            "numFrames": n_frames, "fps": fps,
            "steps": steps,
            "guidance": guidance, "guidanceLowNoise": guidance_low,
            "flowShift": flow_shift, "seed": seed,
            "hasInputImage": bool(req.inputImage),
        }
        source_sha = hashlib.sha256(
            json.dumps(source_payload, sort_keys=True).encode("utf-8")
        ).hexdigest()

        # Optional input image for I2V (or TI2V combined pipeline)
        init_image = None
        if req.inputImage:
            if not CAP_IMAGE2VIDEO:
                raise ValueError("Image-to-video disabled on this runner")
            from PIL import Image
            init_image = Image.open(io.BytesIO(resolve_input_image(req.inputImage))).convert("RGB")
        elif self._is_i2v:
            raise ValueError("This runner serves an image-to-video Wan variant; inputImage is required.")

        # Tune the scheduler for the resolution (flow_shift)
        try:
            from diffusers.schedulers.scheduling_unipc_multistep import UniPCMultistepScheduler
            self.pipeline.scheduler = UniPCMultistepScheduler.from_config(
                self.pipeline.scheduler.config, flow_shift=flow_shift)
        except Exception as e:
            logger.debug(f"flow_shift configuration skipped: {e}")

        generator = torch.Generator(device=self.device).manual_seed(seed)
        kwargs = {
            "prompt":              req.prompt,
            "negative_prompt":     req.negativePrompt or "",
            "width":               width,
            "height":              height,
            "num_frames":          n_frames,
            "num_inference_steps": steps,
            "guidance_scale":      guidance,
            "generator":           generator,
        }
        # Wan 2.2 MoE — pass the second guidance scale when the pipeline accepts it
        if WAN_VARIANT in ("t2v-a14b", "i2v-a14b"):
            kwargs["guidance_scale_2"] = guidance_low
        if init_image is not None:
            kwargs["image"] = init_image

        with torch.no_grad():
            out = self.pipeline(**kwargs)
        # Wan pipelines return obj.frames[0] (list of PIL images or numpy array)
        frames = out.frames[0] if hasattr(out, "frames") else out
        if isinstance(frames, list):
            import numpy as np
            frames = np.stack([np.asarray(f) for f in frames])
        elif hasattr(frames, "shape") and frames.ndim == 5:
            frames = frames[0].permute(0, 2, 3, 1).cpu().numpy()
        elif hasattr(frames, "cpu"):
            frames = frames.cpu().numpy()

        stem    = (req.filenamePrefix or "safebox-wan-video") + "-" + uuid.uuid4().hex[:12]
        out_path = WORK_DIR / f"{stem}.mp4"
        size_bytes = frames_to_mp4(frames, fps, out_path)
        elapsed_ms = int((time.time() - t0) * 1000)
        video_seconds = n_frames / float(fps)

        output_sha = hashlib.sha256(out_path.read_bytes()).hexdigest()

        result: Dict[str, Any] = {
            "model":  MODEL_NAME,
            "prompt": req.prompt,
            "video": {
                "format":      "mp4",
                "codec":       "h264",
                "width":       width,
                "height":      height,
                "numFrames":   n_frames,
                "fps":         fps,
                "durationSec": round(video_seconds, 3),
                "sizeBytes":   size_bytes,
                "hasAudio":    False,
            },
            "sourceSha256": source_sha,
            "outputSha256": output_sha,
            "usage": {
                "steps":            steps,
                "elapsedMs":        elapsed_ms,
                "realTimeFactor":   round(video_seconds / max(elapsed_ms / 1000.0, 0.001), 3),
                "seed":             seed,
                "guidance":         guidance,
                "guidanceLowNoise": guidance_low,
                "flowShift":        flow_shift,
            },
        }
        if req.outputMode == "base64":
            result["video"]["base64"] = base64.b64encode(out_path.read_bytes()).decode("ascii")
        else:
            result["video"]["path"] = str(out_path)
        return result


video_runner = WanVideoRunner()


# ─── Endpoints ─────────────────────────────────────────────────────────

@app.post("/v1/video/generate")
async def v1_video_generate(request: Request):
    global in_flight, request_count, total_frames_generated, total_video_seconds, total_compute_ms

    body_bytes = await request.body()
    if not verify_hmac(request, body_bytes):
        raise HTTPException(status_code=401, detail="HMAC verification failed")
    try:
        req = VideoGenerateRequest(**json.loads(body_bytes))
    except Exception as e:
        raise HTTPException(status_code=400, detail=f"Bad request: {e}")

    if not model_matches(req.model):
        raise HTTPException(status_code=400,
            detail=f"Model '{req.model}' not loaded. This runner serves '{MODEL_NAME}'.")
    if not (CAP_TEXT2VIDEO or CAP_IMAGE2VIDEO):
        raise HTTPException(status_code=400, detail="Video generation disabled.")
    if req.outputMode not in (None, "path", "base64"):
        raise HTTPException(status_code=400, detail=f"Unknown outputMode: {req.outputMode}")
    if not video_runner.ready:
        raise HTTPException(status_code=503, detail="Model is still loading; retry shortly")
    if not req.prompt or not req.prompt.strip():
        raise HTTPException(status_code=400, detail="prompt must be non-empty")
    if in_flight >= MAX_QUEUE_DEPTH:
        raise HTTPException(status_code=503,
            detail=f"Runner at capacity (in_flight={in_flight}, max={MAX_QUEUE_DEPTH}). "
                   f"Wan 2.2 inference is slow — retry in 60s.")

    request_id = request.headers.get("X-Safebox-Request-Id") or str(uuid.uuid4())

    in_flight += 1
    t0 = time.time()
    try:
        result = await asyncio.to_thread(video_runner.generate, req)
        request_count          += 1
        total_frames_generated += result["video"]["numFrames"]
        total_video_seconds    += result["video"]["durationSec"]
        compute_ms = int((time.time() - t0) * 1000)
        total_compute_ms       += compute_ms
        return JSONResponse(content=result,
                            headers=safebox_headers(request_id, MODEL_NAME, compute_ms))
    except HTTPException:
        raise
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))
    except Exception as e:
        logger.exception("Generation failed")
        raise HTTPException(status_code=500, detail=f"Generation failed: {e}")
    finally:
        in_flight -= 1


@app.get("/v1/capabilities")
async def capabilities():
    transport: Dict[str, Any] = {}
    if ENABLE_UNIX_SOCKET:
        transport["socket"] = {
            "path":        SAFEBOX_SOCKET_PATH,
            "permissions": "0660",
            "group":       "safebox-services",
        }
    return {
        "version":    "1.0",
        "runnerType": "video-generation",
        "runnerId":   RUNNER_ID,
        "serviceId":  SERVICE_ID,
        "transport":  transport,
        "models": {
            "loaded":     [MODEL_NAME] if (video_runner.ready and MODEL_NAME) else [],
            "loading":    [MODEL_NAME] if (not video_runner.ready and MODEL_NAME) else [],
            "underlying": WAN_MODEL_PATH,
            "variant":    WAN_VARIANT,
            "architecture": "Mixture-of-Experts diffusion (high-noise + low-noise experts)" if "a14b" in WAN_VARIANT else "single-stream diffusion",
        },
        "capabilities": {
            "text2video":     CAP_TEXT2VIDEO,
            "image2video":    CAP_IMAGE2VIDEO,
            "video2video":    CAP_VIDEO2VIDEO,
            "audio":          CAP_AUDIO,
            "streaming":      CAP_STREAMING,
            "maxNumFrames":   MAX_NUM_FRAMES,
            "outputFormats":  ["mp4"],
            "outputModes":    ["path", "base64"],
        },
        "defaults": {
            "width":             DEFAULT_WIDTH,
            "height":            DEFAULT_HEIGHT,
            "numFrames":         DEFAULT_NUM_FRAMES,
            "fps":               DEFAULT_FPS,
            "steps":             DEFAULT_STEPS,
            "guidance":          DEFAULT_GUIDANCE,
            "guidanceLowNoise":  DEFAULT_GUIDANCE_LOW_NOISE,
            "flowShift":         DEFAULT_FLOW_SHIFT,
        },
        "health": "healthy" if video_runner.ready else "loading",
    }


@app.get("/v1/capacity")
async def capacity():
    return {
        "canAccept":            video_runner.ready and in_flight < MAX_QUEUE_DEPTH,
        "inFlight":             in_flight,
        "maxQueueDepth":        MAX_QUEUE_DEPTH,
        "capacityHint":         get_capacity_hint(),
        "requestCount":         request_count,
        "totalFramesGenerated": total_frames_generated,
        "totalVideoSeconds":    round(total_video_seconds, 3),
        "totalComputeMs":       total_compute_ms,
    }


@app.get("/v1/models")
async def models():
    return {
        "object": "list",
        "data": [
            {
                "id":         MODEL_NAME,
                "object":     "model",
                "owned_by":   "safebox",
                "created":    int(time.time()),
                "underlying": WAN_MODEL_PATH,
                "variant":    WAN_VARIANT,
            }
        ] if MODEL_NAME else [],
    }


@app.get("/health")
async def health():
    return Response(
        content=json.dumps({
            "status":             "healthy" if video_runner.ready else "loading",
            "modelReady":         video_runner.ready,
            "requestCount":       request_count,
            "inFlight":           in_flight,
            "totalVideoSeconds":  round(total_video_seconds, 3),
        }),
        status_code=200 if video_runner.ready else 503,
        media_type="application/json",
    )


# ─── Socket setup ──────────────────────────────────────────────────────
def setup_unix_socket():
    if not ENABLE_UNIX_SOCKET:
        return
    sp = Path(SAFEBOX_SOCKET_PATH)
    sp.parent.mkdir(parents=True, exist_ok=True)
    if sp.exists():
        logger.info(f"Removing stale socket: {sp}")
        sp.unlink()


@app.on_event("startup")
async def on_startup():
    logger.info(f"Wan 2.2 runner starting — model={MODEL_NAME!r} variant={WAN_VARIANT}")
    setup_unix_socket()
    asyncio.get_event_loop().run_in_executor(None, video_runner.load)


# ─── Main ──────────────────────────────────────────────────────────────
if __name__ == "__main__":
    if ENABLE_UNIX_SOCKET:
        async def _adjust_perms():
            sp = Path(SAFEBOX_SOCKET_PATH)
            for _ in range(50):
                if sp.exists():
                    os.chmod(str(sp),
                             stat.S_IRUSR | stat.S_IWUSR | stat.S_IRGRP | stat.S_IWGRP)
                    try:
                        import grp, pwd
                        gid = grp.getgrnam("safebox-services").gr_gid
                        uid = pwd.getpwnam("safebox-services").pw_uid
                        os.chown(str(sp), uid, gid)
                    except Exception as e:
                        logger.warning(f"Could not chown socket: {e}")
                    break
                await asyncio.sleep(0.1)
        @app.on_event("startup")
        async def _perms_on_startup():
            asyncio.create_task(_adjust_perms())
        logger.info(f"Listening on Unix socket: {SAFEBOX_SOCKET_PATH}")
        uvicorn.run(app, uds=SAFEBOX_SOCKET_PATH, log_level="info")
    else:
        logger.info("Listening on 0.0.0.0:8080 (no Unix socket)")
        uvicorn.run(app, host="0.0.0.0", port=8080, log_level="info")
